version: "3.8"

services:
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: foodfast-user-service
    restart: "no"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-12345
      - JWT_EXPIRES_IN=1d
      - DB_HOST=db          
      - DB_PORT=5432
      - DB_USER=foodfast
      - DB_PASSWORD=123456
      - DB_NAME=foodfastdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    volumes:
      # Mount mã nguồn, trừ node_modules
      - ./services/user-service:/usr/src/app
      # Dòng này cách ly node_modules bên trong container
      - /usr/src/app/node_modules
    networks:
      - backend

  db:
    image: postgres:16
    container_name: foodfast-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: foodfast
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: foodfastdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: foodfast-redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - backend

  adminer:
    image: adminer:latest
    container_name: foodfast-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  pgdata:
  redisdata:

networks:
  backend:
    driver: bridge